### ISSUE TITLE
`cargo test` command not working on Windows

### ISSUE THREAD

**Issue by CHOUMnote** [lablup/raftify#107]
I am trying to run raftify on Windows 11. To perform a preliminary check, I used the `cargo test` command, but it resulted in errors during the test cases.

The error message is as follows:

```
......

running 2 tests
test test_dynamic_bootstrap ... FAILED
test test_static_bootstrap ... FAILED

failures:

---- test_dynamic_bootstrap stdout ----
thread 'test_dynamic_bootstrap' panicked at harness\src\utils.rs:116:10:
Failed to execute lsof command: Error { kind: NotFound, message: "program not found" }

---- test_static_bootstrap stdout ----
thread 'test_static_bootstrap' panicked at harness\src\utils.rs:116:10:
Failed to execute lsof command: Error { kind: NotFound, message: "program not found" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_dynamic_bootstrap
    test_static_bootstrap

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p harness --test bootstrap`
```

I discovered that this issue is due to the `lsof` command not being supported on Windows. To resolve this issue and address #105, I believe the OS-dependent tests need to be fixed.

**Comment by jopemachine** [comment]
Resolved in https://github.com/lablup/raftify/pull/108.
